version: "3.7"

services:
    db:
        image: neo4j:latest
        ports:
          - 7474:7474
          - 7687:7687
        volumes:
          - ${DB_PATH}/conf:/conf
          - ${DB_PATH}/data:/data
          - ${DB_PATH}/logs:/logs
          - ${DB_PATH}/plugins:/plugins
        environment:
          - NEO4J_AUTH=neo4j/password
          - NEO4J_dbms_memory_pagecache_size=1G
          - NEO4J_dbms.memory.heap.initial_size=2G
          - NEO4J_dbms_memory_heap_max__size=2G
          - NEO4J_dbms_security_procedures_unrestricted=apoc.*
          - NEO4J_dbms_security_procedures_whitelist=apoc.*
    app:
        image: phylodb:latest
        ports:
            - 8080:8080
        volumes:
            - ${APP_PATH}/logs:/logs